
const mongoose = require("mongoose");
const Naija = require("./model/naija");



mongoose.connect('mongodb://0.0.0.0:27017/nigerianAtlasDB', {useNewUrlParser: true, useUnifiedTopology: true})
.then(() => {
    console.log("Mongo connection open");
})
.catch(err =>{
    console.log('Mongo connection error');
    console.log(err);
})

// const deleteMany =async()=>{
//     await Naija.deleteMany({});
// } 

// deleteMany();

const p = new Naija({
state:{
    Abia:{
        "NoOfLocalGovtAreas":18,
        "capital": "Umuahia",
        "slogan": "God's Own State",
        "governor": "Okezie Ikpeazu",
        "geoPoliticalZone": "South East",
        "population(2006)": 2833999,
        "landmass(km^2)": 5420,
        "populationDensity(km^2)": 441,
        "localGovtAreas":[
            "Aba North",
            "Aba South",
            "Arochukwu",
            "Bende",
            "Ikwuano",
            "Isiala-Ngwa North",
            "Isiala-Ngwa South",
            "Isuikwato",
            "Obi Nwa",
            "Ohafia",
            "Osisioma",
            "Ngwa",
            "Ugwunagbo",
            "Ukwa East",
            "Ukwa West",
            "Umuahia North",
            "Umuahia South",
            "Umu-Neochi"
                        ]
            },

    Adamawa:{
        "NoOfLocalGovtAreas":21,
        "capital": "Yola",
        "slogan": "Land of Beauty",
        "governor": "Ahmadu Umaru Fintiri",
        "geoPoliticalZone": "Noth East",
        "population(2006)": 3168101,
        "landmass(km^2)": 36917,
        "populationDensity(km^2)": 86,
        "localGovtAreas":[
            "Demsa",
            "Fufore",
            "Ganaye",
            "Gireri",
            "Gombi",
            "Guyuk",
            "Hong",
            "Jada",
            "Lamurde",
            "Madagali",
            "Maiha",
            "Mayo-Belwa",
            "Michika",
            "Mubi North",
            "Mubi South",
            "Numan",
            "Shelleng",
            "Song",
            "Toungo",
            "Yola North",
            "Yola South"
                        ]
            },
    AkwaIbom:{
        "NoOfLocalGovtAreas":31,
        "capital": "Uyo",
        "slogan": "Land of Promise",
        "governor": "Udom Gabriel Emmanuel",
        "geoPoliticalZone": "South East",
        "population(2006)": 3920208,
        "landmass(km^2)": 6187,
        "populationDensity(km^2)": 634,
        "localGovtAreas":[
            "Abak",
            "Eastern Obolo",
            "Eket",
            "Esit Eket",
            "Essien Udim",
            "Etim Ekpo",
            "Etinan",
            "Ibeno",
            "Ibesikpo Asutan",
            "Ibiono Ibom",
            "Ika",
            "Ikono",
            "Ikot Abasi",
            "Ikot Ekpene",
            "Ini",
            "Itu",
            "Mbo",
            "Mkpat Enin",
            "Nsit Atai",
            "Nsit Ibom",
            "Nsit Ubium",
            "Obot Akara",
            "Okobo",
            "Onna",
            "Oron",
            "Oruk Anam",
            "Udung Uko",
            "Ukanafun",
            "Uruan",
            "Urue-Offong/Oruko ",
            "Uyo"
                        ]
            },

    Bauchi:{
        "NoOfLocalGovtAreas":19,
        "capital": "Bauchi",
        "slogan": "Pearl of Tourism",
        "governor": "Bala Abdulkadir Mohammed",
        "geoPoliticalZone": "North East",
        "population(2006)": 4676465,
        "landmass(km^2)": 64605,
        "populationDensity(km^2)": 72,
        "localGovtAreas":[
            "Alkaleri",
            "Bauchi",
            "Bogoro",
            "Damban",
            "Darazo",
            "Dass",
            "Ganjuwa",
            "Giade",
            "Itas/Gadau",
            "Jama'are",
            "Katagum",
            "Kirfi",
            "Misau",
            "Ningi",
            "Shira",
            "Tafawa-Balewa",
            "Toro",
            "Warji",
            "Zaki"
                        ]
            },


    Bayelsa:{
        "NoOfLocalGovtAreas":8,
        "capital": "Yenegoa",
        "slogan": "Glory of all lands",
        "governor": "Douye Diri",
        "geoPoliticalZone": "South South",
        "population(2006)": 1703358,
        "landmass(km^2)": 10773,
        "populationDensity(km^2)": 158,
        "localGovtAreas":[
            "Brass",
            "Ekeremor",
            "Kolokuma/Opokuma",
            "Nembe",
            "Ogbia",
            "Sagbama",
            "Southern Jaw",
            "Yenegoa"
                        ]
            },

            Benue:{
                "NoOfLocalGovtAreas":23,
                "capital": "Makurdi",
                "slogan": "Food Basket of the Nation",
                "governor": "Samuel Ortom",
                "geoPoliticalZone": "North Central",
                "population(2006)": 4219244,
                "landmass(km^2)": 34059,
                "populationDensity(km^2)": 124,
                "localGovtAreas":[
                    "Ado",
                    "Agatu",
                    "Apa",
                    "Buruku",
                    "Gboko",
                    "Guma",
                    "Gwer East",
                    "Gwer West",
                    "Katsina-Ala",
                    "Konshisha",
                    "Kwande",
                    "Logo",
                    "Makurdi",
                    "Obi",
                    "Ogbadibo",
                    "Oju",
                    "Okpokwu",
                    "Ohimini",
                    "Oturkpo",
                    "Tarka",
                    "Ukum",
                    "Ushongo",
                    "Vandeikya"
              ]},
              
            Borno:{
                "NoOfLocalGovtAreas":27,
                "capital": "Maiduguri",
                "slogan": "Home of Peace",
                "governor": "Babagana Umara Zulum",
                "geoPoliticalZone": "North East",
                "population(2006)": 4151193,
                "landmass(km^2)": 71130,
                "populationDensity(km^2)": 58,
                "localGovtAreas":[
                    "Abadam",
                    "Askira/Uba",
                    "Bama",
                    "Bayo",
                    "Biu",
                    "Chibok",
                    "Damboa",
                    "Dikwa",
                    "Gubio",
                    "Guzamala",
                    "Gwoza",
                    "Hawul",
                    "Jere",
                    "Kaga",
                    "Kala/Balge",
                    "Konduga",
                    "Kukawa",
                    "Kwaya Kusar",
                    "Mafa",
                    "Magumeri",
                    "Maiduguri",
                    "Marte",
                    "Mobbar",
                    "Monguno",
                    "Ngala",
                    "Nganzai",
                    "Shani"
              ]},


              CrossRiver:{
                "NoOfLocalGovtAreas":18,
                "capital": "Calabar",
                "slogan": "The People's Paradise",
                "governor": "Benedict Ayade",
                "geoPoliticalZone": "South South",
                "population(2006)": 2888966,
                "landmass(km^2)": 21050,
                "populationDensity(km^2)": 137,
                "localGovtAreas":[
                    "Akpabuyo",
                    "Odukpani",
                    "Akamkpa",
                    "Biase",
                    "Abi",
                    "Ikom",
                    "Yarkur",
                    "Odubra",
                    "Boki",
                    "Ogoja",
                    "Yala",
                    "Obanliku",
                    "Obudu",
                    "Calabar South",
                    "Etung",
                    "Bekwara",
                    "Bakassi",
                    "Calabar Municipality"
              ]},

              Delta:{
                "NoOfLocalGovtAreas":25,
                "capital": "Asaba",
                "slogan": "The Big Heart",
                "governor": "Ifeanyi Okowa",
                "geoPoliticalZone": "South South",
                "population(2006)": 4098391,
                "landmass(km^2)": 18050,
                "populationDensity(km^2)": 227,
                "localGovtAreas":[
                    "Oshimili",
                    "Aniocha",
                    "Aniocha South",
                    "Ika South",
                    "Ika North-East",
                    "Ndokwa West",
                    "Ndokwa East",
                    "Isoko south",
                    "Isoko North",
                    "Bomadi",
                    "Burutu",
                    "Ughelli South",
                    "Ughelli North",
                    "Ethiope West",
                    "Ethiope East",
                    "Sapele",
                    "Okpe",
                    "Warri North",
                    "Warri South",
                    "Uvwie",
                    "Udu",
                    "Warri Central",
                    "Ukwani",
                    "Oshimili North",
                    "Patani"
            ]},

            Ebonyi:{
                "NoOfLocalGovtAreas":12,
                "capital": "Abakaliki",
                "slogan": "Salt of the Nation",
                "governor": "Dave Umahi",
                "geoPoliticalZone": "South East",
                "population(2006)": 2173501,
                "landmass(km^2)": 5530,
                "populationDensity(km^2)": 393,
                "localGovtAreas":[
                    "Afikpo South",
                    "Afikpo North",
                    "Onicha",
                    "Ohaozara",
                    "Abakaliki",
                    "Ishielu",
                    "lkwo",
                    "Ezza",
                    "Ezza South",
                    "Ohaukwu",
                    "Ebonyi",
                    "Ivo"
                ]},

                Enugu:{
                    "NoOfLocalGovtAreas":16,
                    "capital": "Enugu",
                    "slogan": "Coal City State",
                    "governor": "Ifeanyi Ugwuanyi",
                    "geoPoliticalZone": "South East",
                    "population(2006)": 3257298,
                    "landmass(km^2)": 12440,
                    "populationDensity(km^2)": 262,
                    "localGovtAreas":[
                        "Enugu South,",
                        "Igbo-Eze South",
                        "Enugu North",
                        "Nkanu",
                        "Udi Agwu",
                        "Oji-River",
                        "Ezeagu",
                        "IgboEze North",
                        "Isi-Uzo",
                        "Nsukka",
                        "Igbo-Ekiti",
                        "Uzo-Uwani",
                        "Enugu Eas",
                        "Aninri",
                        "Nkanu East",
                        "Udenu"
                ]},

                Edo:{
                    "NoOfLocalGovtAreas":15,
                    "capital": "Benin city",
                    "slogan": "Heart Beat of Nigeria",
                    "governor": "Godwin Obaseki",
                    "geoPoliticalZone": "South South",
                    "population(2006)": 3218332,
                    "landmass(km^2)": 17450,
                    "populationDensity(km^2)": 184,
                    "localGovtAreas":[
                        "Esan North-East",
                        "Esan Central",
                        "Esan West",
                        "Egor",
                        "Ukpoba",
                        "Central",
                        "Etsako Central",
                        "Igueben",
                        "Oredo",
                        "Ovia SouthWest",
                        "Ovia South-East",
                        "Orhionwon",
                        "Uhunmwonde",
                        "Etsako East",
                        "Esan South-East"
                ]},


                Ekiti:{
                    "NoOfLocalGovtAreas":16,
                    "capital": "Ado-Ekiti",
                    "slogan": "Land of Honour and Integrity",
                    "governor": "Abiodun Abayomi Oyebanji",
                    "geoPoliticalZone": "South West",
                    "population(2006)": 2384212,
                    "landmass(km^2)": 6353,
                    "populationDensity(km^2)": 375,
                    "localGovtAreas":[
                        "Ado",
                        "Ekiti-East",
                        "Ekiti-West",
                        "Emure/Ise/Orun",
                        "Ekiti South-West",
                        "Ikere Ekiti",
                        "Irepodun",
                        "Ijero,",
                        "Ido/Osi",
                        "Oye",
                        "Ikole",
                        "Moba",
                        "Gbonyin",
                        "Efon",
                        "Ise/Orun",
                        "Ilejemeje"
                ]},


                FCTAbuja:{
                    "NoOfLocalGovtAreas":6,
                    "capital": "",
                    "slogan": "",
                    "governor": "Muhammed Bello",
                    "geoPoliticalZone": "North Central",
                    "population(2006)": 1405201,
                    "landmass(km^2)": 7315,
                    "populationDensity(km^2)": 192,
                    "localGovtAreas":[
                        "Abaji",
                        "Abuja Municipal",
                        "Bwari",
                        "Gwagwalada",
                        "Kuje",
                        "Kwali"
                ]},

                Gombe:{
                    "NoOfLocalGovtAreas":11,
                    "capital": "Gombe",
                    "slogan": "Jewel in the Savannah",
                    "governor": "Muhammad Inuwa Yahaya",
                    "geoPoliticalZone": "North East",
                    "population(2006)": 2353879,
                    "landmass(km^2)": 18768,
                    "populationDensity(km^2)": 125,
                    "localGovtAreas":[
                            "Akko",
                            "Balanga",
                            "Billiri",
                            "Dukku",
                            "Kaltungo",
                            "Kwami",
                            "Shomgom",
                            "Funakaye",
                            "Gombe",
                            "Nafada/Bajoga",
                            "Yamaltu/Delta"
                    ]},
                    Imo:{
                        "NoOfLocalGovtAreas":27,
                        "capital": "Owerri",
                        "slogan": "Eastern Heartland",
                        "governor": "Hope Odidika Uzodinma",
                        "geoPoliticalZone": "South East",
                        "population(2006)": 3934899,
                        "landmass(km^2)": 5430,
                        "populationDensity(km^2)": 725,
                        "localGovtAreas":[
                            "Aboh-Mbaise",
                            "Ahiazu-Mbaise",
                            "Ehime-Mbano",
                            "Ezinihitte",
                            "Ideato North",
                            "Ideato South",
                            "Ihitte/Uboma",
                            "Ikeduru",
                            "Isiala Mbano",
                            "Isu",
                            "Mbaitoli",
                            "Mbaitoli",
                            "Ngor-Okpala",
                            "Njaba",
                            "Nwangele",
                            "Nkwerre",
                            "Obowo",
                            "Oguta",
                            "Ohaji/Egbema",
                            "Okigwe",
                            "Orlu",
                            "Orsu",
                            "Oru East",
                            "Oru West",
                            "Owerri-Municipal",
                            "Owerri North",
                            "Owerri West"
                    ]},

                    Jigawa:{
                        "NoOfLocalGovtAreas":26,
                        "capital": "Dutse",
                        "slogan": "The New World",
                        "governor": "Badaru Abubakar",
                        "geoPoliticalZone": "North West",
                        "population(2006)": 4348649,
                        "landmass(km^2)": 22605,
                        "populationDensity(km^2)": 192,
                        "localGovtAreas":[
                            "Auyo",
                            "Babura",
                            "Birni Kudu",
                            "Biriniwa",
                            "Buji",
                            "Dutse",
                            "Gagarawa",
                            "Garki",
                            "Gumel",
                            "Guri",
                            "Gwaram",
                            "Gwiwa",
                            "Hadejia",
                            "Jahun",
                            "Kafin Hausa",
                            "Kaugama Kazaure",
                            "Kiri Kasamma",
                            "Kiyawa",
                            "Maigatari",
                            "Malam Madori",
                            "Miga",
                            "Ringim",
                            "Roni",
                            "Sule-Tankarkar",
                            "Taura",
                            "Yankwashi"
                    ]},

                    Kaduna:{
                        "NoOfLocalGovtAreas":23,
                        "capital": "Zaria",
                        "slogan": "Centre of Learning",
                        "governor": "Nasir Ahmad el-Rufai",
                        "geoPoliticalZone": "North West",
                        "population(2006)": 6066562,
                        "landmass(km^2)": 43460,
                        "populationDensity(km^2)": 140,
                        "localGovtAreas":[
                            "Birni-Gwari",
                            "Chikun",
                            "Giwa",
                            "Igabi",
                            "Ikara",
                            "jaba",
                            "Jema'a",
                            "Kachia",
                            "Kaduna North",
                            "Kaduna South",
                            "Kagarko",
                            "Kajuru",
                            "Kaura",
                            "Kauru",
                            "Kubau",
                            "Kudan",
                            "Lere",
                            "Makarfi",
                            "Sabon-Gari",
                            "Sanga",
                            "Soba",
                            "Zango-Kataf",
                            "Zaria"
                    ]},

                    Kano:{
                        "NoOfLocalGovtAreas":45,
                        "capital": "Kano",
                        "slogan": "Centre of Commerce",
                        "governor": "Abdullahi Umar Ganduje",
                        "geoPoliticalZone": "North West",
                        "population(2006)": 9383682,
                        "landmass(km^2)": 20680,
                        "populationDensity(km^2)": 454,
                        "localGovtAreas":[
                            "Ajingi",
                            "Albasu",
                            "Bagwai",
                            "Bebeji",
                            "Bichi",
                            "Bunkure",
                            "Dala",
                            "Dambatta",
                            "Dawakin Kudu",
                            "Dawakin Tofa",
                            "Doguwa",
                            "Fagge",
                            "Gabasawa",
                            "Garko",
                            "Garum",
                            "Mallam",
                            "Gaya",
                            "Gezawa",
                            "Gwale",
                            "Gwarzo",
                            "Kabo",
                            "Kano Municipal",
                            "Karaye",
                            "Kibiya",
                            "Kiru",
                            "kumbotso",
                            "Kunchi",
                            "Kura",
                            "Madobi",
                            "Makoda",
                            "Minjibir",
                            "Nasarawa",
                            "Rano",
                            "Rimin Gado",
                            "Rogo",
                            "Shanono",
                            "Sumaila",
                            "Takali",
                            "Tarauni",
                            "Tofa",
                            "Tsanyawa",
                            "Tudun Wada",
                            "Ungogo",
                            "Warawa",
                            "Wudil"
                    ]},


                    Katsina:{
                        "NoOfLocalGovtAreas":34,
                        "capital": "Katsina",
                        "slogan": "Home of Hospitality",
                        "governor": "Aminu Bello Masari",
                        "geoPoliticalZone": "North West",
                        "population(2006)": 5792578,
                        "landmass(km^2)": 26785,
                        "populationDensity(km^2)": 216,
                        "localGovtAreas":[
                            "Bakori",
                            "Batagarawa",
                            "Batsari",
                            "Baure",
                            "Bindawa",
                            "Charanchi",
                            "Dandume",
                            "Danja",
                            "Dan Musa",
                            "Daura",
                            "Dutsi",
                            "Dutsin-Ma",
                            "Faskari",
                            "Funtua",
                            "Ingawa",
                            "Jibia",
                            "Kafur",
                            "Kaita",
                            "Kankara",
                            "Kankia",
                            "Katsina",
                            "Kurfi",
                            "Kusada",
                            "Mai'Adua",
                            "Malumfashi",
                            "Mani",
                            "Mashi",
                            "Matazuu",
                            "Musawa",
                            "Rimi",
                            "Sabuwa",
                            "Safana",
                            "Sandamu",
                            "Zango"
                    ]},

                    Kebbi:{
                        "NoOfLocalGovtAreas":21,
                        "capital": "Birnin Kebbi",
                        "slogan": "Land of Equity",
                        "governor": "Abubakar Atiku Bagudu",
                        "geoPoliticalZone": "North West",
                        "population(2006)": 3238628,
                        "landmass(km^2)": 41855,
                        "populationDensity(km^2)": 77,
                        "localGovtAreas":[
                            "Aleiro",
                            "Arewa-Dandi",
                            "Argungu",
                            "Augie",
                            "Bagudo",
                            "Birnin Kebbi",
                            "Bunza",
                            "Dandi",
                            "Fakai",
                            "Gwandu",
                            "Jega",
                            "Kalgo",
                            "Koko/Besse",
                            "Maiyama",
                            "Ngaski",
                            "Sakaba",
                            "Shanga",
                            "Suru",
                            "Wasagu/Danko",
                            "Yauri",
                            "Zuru"
                    ]},

                    Kogi:{
                        "NoOfLocalGovtAreas":21,
                        "capital": "Lokoja",
                        "slogan": "The Confluence State",
                        "governor": "Yahaya Adoza Bello",
                        "geoPoliticalZone": "North Central",
                        "population(2006)": 3278487,
                        "landmass(km^2)": 32440,
                        "populationDensity(km^2)": 284,
                        "localGovtAreas":[
                            "Adavi",
                            "Ajaokuta",
                            "Ankpa",
                            "Bassa",
                            "Dekina",
                            "Ibaji",
                            "Idah",
                            "Igalamela-Odolu",
                            "Ijumu",
                            "Kabba/Bunu",
                            "Kogi",
                            "Lokoja",
                            "Mopa-Muro",
                            "Ofu",
                            "Ogori/Mangongo",
                            "Okehi",
                            "Okene",
                            "Olamabolo",
                            "Omala",
                            "Yagba East",
                            "Yagba West"
                    ]},

                    Kwara:{
                        "NoOfLocalGovtAreas":15,
                        "capital": "Ilorin",
                        "slogan": "State of Harmony",
                        "governor": "Abdul Rahman Abdul Razaq",
                        "geoPoliticalZone": "South West",
                        "population(2006)": 3278487,
                        "landmass(km^2)": 32440,
                        "populationDensity(km^2)": 284,
                        "localGovtAreas":[
                            "Asa",
                            "Baruten",
                            "Edu",
                            "Ekiti",
                            "Ifelodun",
                            "Ilorin East",
                            "Ilorin West",
                            "Irepodun",
                            "Isin",
                            "Kaiama",
                            "Moro",
                            "Offa",
                            "Oke-Ero",
                            "Oyun",
                            "Pategi"
                    ]},

                    Lagos:{
                        "NoOfLocalGovtAreas":20,
                        "capital": "Ikeja",
                        "slogan": "Centre of Excellence",
                        "governor": "Babajide Olusola Sanwo-Olu",
                        "geoPoliticalZone": "South West",
                        "population(2006)": 9013534,
                        "landmass(km^2)": 3345,
                        "populationDensity(km^2)": 2695,
                        "localGovtAreas":[
                            "Agege",
                            "Ajeromi-Ifelodun",
                            "Alimosho",
                            "Amuwo-Odofin",
                            "Apapa",
                            "Badagry",
                            "Epe",
                            "Eti-Osa",
                            "Ibeju/Lekki",
                            "Ifako-Ijaye",
                            "Ikeja",
                            "Ikorodu",
                            "Kosofe",
                            "Lagos Island",
                            "Lagos Mainland",
                            "Mushin",
                            "Ojo",
                            "Oshodi-Isolo",
                            "Shomolu",
                            "Surulere"
                    ]},

                    Nasarawa:{
                        "NoOfLocalGovtAreas":13,
                        "capital": "Lafia",
                        "slogan": "Home of Solid Minerals",
                        "governor": "Abdullahi Sule",
                        "geoPoliticalZone": "North Central",
                        "population(2006)": 1863275,
                        "landmass(km^2)": 27117,
                        "populationDensity(km^2)": 69,
                        "localGovtAreas":[
                            "Akwanga",
                            "Awe",
                            "Doma",
                            "Karu",
                            "Keana",
                            "Keffi",
                            "Kokona",
                            "Lafia",
                            "Nasarawa",
                            "Nasarawa-Eggon",
                            "Obi",
                            "Toto",
                            "Wamba"
                    ]},

                    Niger:{
                        "NoOfLocalGovtAreas":25,
                        "capital": "Minna",
                        "slogan": "The Power State",
                        "governor": "Abubakar Sani Bello",
                        "geoPoliticalZone": "North Central",
                        "population(2006)": 3950249,
                        "landmass(km^2)": 13930,
                        "populationDensity(km^2)": 284,
                        "localGovtAreas":[
                            "Agaie",
                            "Agwara",
                            "Bida",
                            "Borgu",
                            "Bosso",
                            "Chanchaga",
                            "Edati",
                            "Gbako",
                            "Gurara",
                            "Katcha",
                            "Kontagora",
                            "Lapai",
                            "Lavun",
                            "Magama",
                            "Mariga",
                            "Mashegu",
                            "Mokwa",
                            "Muya",
                            "Pailoro",
                            "Rafi",
                            "Rijau",
                            "Shiroro",
                            "Suleja",
                            "Tafa",
                            "Wushishi"
                    ]},

                    Ogun:{
                        "NoOfLocalGovtAreas":20,
                        "capital": "Abeokuta",
                        "slogan": "Gateway State",
                        "governor": "Dapo Abiodun",
                        "geoPoliticalZone": "South West",
                        "population(2006)": 3728098,
                        "landmass(km^2)": 16762,
                        "populationDensity(km^2)": 222,
                        "localGovtAreas":[
                            "Abeokuta North",
                            "Abeokuta South",
                            "Ado-Odo/Ota",
                            "Egbado North",
                            "Egbado South",
                            "Ewekoro",
                            "Ifo",
                            "Ijebu East",
                            "Ijebu North",
                            "Ijebu North East",
                            "Ijebu Ode",
                            "Ikenne",
                            "Imeko-Afon",
                            "Ipokia",
                            "Obafemi-Owode",
                            "Ogun Waterside",
                            "Odeda",
                            "Odogbolu",
                            "Remo North",
                            "Shagamu"
                    ]},

                    Ondo:{
                        "NoOfLocalGovtAreas":19,
                        "capital": "Akure",
                        "slogan": "Sunshine State",
                        "governor": "Rotimi Akeredolu",
                        "geoPoliticalZone": "South West",
                        "population(2006)": 3441024,
                        "landmass(km^2)": 14606,
                        "populationDensity(km^2)": 236,
                        "localGovtAreas":[
                            "Akoko North East",
                            "Akoko North West",
                            "Akoko South Akure East",
                            "Akoko South West",
                            "Akure North",
                            "Akure South",
                            "Ese-Odo",
                            "Idanre",
                            "Ifedore",
                            "Ilaje",
                            "Ile-Oluji",
                            "Okeigbo",
                            "Irele",
                            "Odigbo",
                            "Okitipupa",
                            "Ondo East",
                            "Ondo West",
                            "Ose",
                            "Owo"
                    ]},

                    Osun:{
                        "NoOfLocalGovtAreas":30,
                        "capital": "Oshogbo",
                        "slogan": "The State of the Living Spring",
                        "governor": "Ademola Nurudeen Adeleke",
                        "geoPoliticalZone": "South West",
                        "population(2006)": 3423535,
                        "landmass(km^2)": 10245,
                        "populationDensity(km^2)": 334,
                        "localGovtAreas":[
                            "Aiyedade",
                            "Aiyedire",
                            "Atakumosa East",
                            "Atakumosa West",
                            "Boluwaduro",
                            "Boripe",
                            "Ede North",
                            "Ede South",
                            "Egbedore",
                            "Ejigbo",
                            "Ife Central",
                            "Ife East",
                            "Ife North",
                            "Ife South",
                            "Ifedayo",
                            "Ifelodun",
                            "Ila",
                            "Ilesha East",
                            "Ilesha West",
                            "Irepodun",
                            "Irewole",
                            "Isokan",
                            "Iwo",
                            "Obokun",
                            "Odo-Otin",
                            "Ola-Oluwa",
                            "Olorunda",
                            "Oriade",
                            "Orolu",
                            "Osogbo"
                    ]},


                    Oyo:{
                        "NoOfLocalGovtAreas":32,
                        "capital": "Ibadan",
                        "slogan": "Pace Setter State",
                        "governor": "Oluseyi Abiodun Makinde",
                        "geoPoliticalZone": "South West",
                        "population(2006)": 5591589,
                        "landmass(km^2)": 27460,
                        "populationDensity(km^2)": 204,
                        "localGovtAreas":[
                            "Afijio",
                            "Akinyele",
                            "Atiba",
                            "Atigbo",
                            "Egbeda",
                            "Ibadan Central",
                            "Ibadan North",
                            "Ibadan North West",
                            "Ibadan South East",
                            "Ibadan South West",
                            "Ibarapa Central",
                            "Ibarapa East",
                            "Ibarapa North",
                            "Ido",
                            "Irepo",
                            "Iseyin",
                            "Itesiwaju",
                            "Iwajowa",
                            "Kajola",
                            "Lagelu Ogbomosho North",
                            "Ogbomosho South",
                            "Ogo Oluwa",
                            "Olorunsogo",
                            "Oluyole",
                            "Ona-Ara",
                            "Orelope",
                            "Ori Ire",
                            "Oyo East",
                            "Oyo West",
                            "Saki East",
                            "Saki West",
                            "Surulere"
                    ]},

                    Plateau:{
                        "NoOfLocalGovtAreas":17,
                        "capital": "Jos",
                        "slogan": "Home of Peace and Tourism",
                        "governor": "Simon Lalong",
                        "geoPoliticalZone": "North Central",
                        "population(2006)": 3178712,
                        "landmass(km^2)": 58030,
                        "populationDensity(km^2)": 55,
                        "localGovtAreas":[
                            "Barikin Ladi",
                            "Bassa",
                            "Bokkos",
                            "Jos East",
                            "Jos North",
                            "Jos South",
                            "Kanam",
                            "Kanke",
                            "Langtang North",
                            "Langtang South",
                            "Mangu",
                            "Mikang",
                            "Pankshin",
                            "Qua'an Pan",
                            "Riyom",
                            "Shendam",
                            "Wase"
                    ]},

                    Rivers:{
                        "NoOfLocalGovtAreas":23,
                        "capital": "Port-Harcourt",
                        "slogan": "Treasure Base of the Nation",
                        "governor": "Ezenwo Nyesom Wike",
                        "geoPoliticalZone": "South South",
                        "population(2006)": 5185400,
                        "landmass(km^2)": 11077,
                        "populationDensity(km^2)": 468,
                        "localGovtAreas":[
                            "Abua/Odual",
                            "Ahoada East",
                            "Ahoada West",
                            "Akuku Toru",
                            "Andoni",
                            "Asari-Toru",
                            "Bonny",
                            "Degema",
                            "Emohua",
                            "Eleme",
                            "Etche",
                            "Gokana",
                            "Ikwerre",
                            "Khana",
                            "Obia/Akpor",
                            "Ogba/Egbema/Ndoni",
                            "Ogu/Bolo",
                            "Okrika",
                            "Omumma",
                            "Opobo/Nkoro",
                            "Oyigbo",
                            "Port-Harcourt",
                            "Tai"
                    ]},

                    Sokoto:{
                        "NoOfLocalGovtAreas":23,
                        "capital": "Sokoto",
                        "slogan": "Seat of the Caliphate",
                        "governor": "Aminu Waziri Tambuwal",
                        "geoPoliticalZone": "North West",
                        "population(2006)": 3696999,
                        "landmass(km^2)": 25973,
                        "populationDensity(km^2)": 142,
                        "localGovtAreas":[
                            "Binji",
                            "Bodinga",
                            "Dange-shnsi",
                            "Gada",
                            "Goronyo",
                            "Gudu",
                            "Gawabawa",
                            "Illela",
                            "Isa",
                            "Kware",
                            "kebbe",
                            "Rabah",
                            "Sabon birni",
                            "Shagari",
                            "Silame",
                            "Sokoto North",
                            "Sokoto South",
                            "Tambuwal",
                            "Tqngaza",
                            "Tureta",
                            "Wamako",
                            "Wurno",
                            "Yabo"
                    ]},

                    Taraba:{
                        "NoOfLocalGovtAreas":16,
                        "capital": "Jalingo",
                        "slogan": "Nature's Gift to the Nation",
                        "governor": "Darius Ishaku",
                        "geoPoliticalZone": "North East",
                        "population(2006)": 2300736,
                        "landmass(km^2)": 55920,
                        "populationDensity(km^2)": 54,
                        "localGovtAreas":[
                            "Ardo-kola",
                            "Bali",
                            "Donga",
                            "Gashaka",
                            "Cassol",
                            "Ibi",
                            "Jalingo",
                            "Karin-Lamido",
                            "Kurmi",
                            "Lau",
                            "Sardauna",
                            "Takum",
                            "Ussa",
                            "Wukari",
                            "Yorro",
                            "Zing"
                    ]},


                    Yobe:{
                        "NoOfLocalGovtAreas":17,
                        "capital": "Damaturu",
                        "slogan": "Nature's Gift to the Nation",
                        "governor": "Mai Mala Buni",
                        "geoPoliticalZone": "North East",
                        "population(2006)": 2321591,
                        "landmass(km^2)": 45270,
                        "populationDensity(km^2)": 51,
                        "localGovtAreas":[
                            "Bade",
                            "Bursari",
                            "Damaturu",
                            "Fika",
                            "Fune",
                            "Geidam",
                            "Gujba",
                            "Gulani",
                            "Jakusko",
                            "Karasuwa",
                            "Karawa",
                            "Machina",
                            "Nangere",
                            "Nguru Potiskum",
                            "Tarmua",
                            "Yunusari",
                            "Yusufari"
                    ]},

                    Zamfara:{
                        "NoOfLocalGovtAreas":15,
                        "capital": "Gusau",
                        "slogan": "Farming is Our Pride",
                        "governor": "Bello Muhammad Mutawalle",
                        "geoPoliticalZone": "North West",
                        "population(2006)": 3259846,
                        "landmass(km^2)": 39762,
                        "populationDensity(km^2)": 82,
                        "localGovtAreas":[
                            "Anka",
                            "Bakura",
                            "Birnin Magaji",
                            "Bukkuyum",
                            "Bungudu",
                            "Gummi",
                            "Gusau",
                            "Kaura",
                            "Namoda",
                            "Maradun",
                            "Maru",
                            "Shinkafi",
                            "Talata Mafara",
                            "Tsafe",
                            "Zurmi"
                    ]}
                
        }
});
p.save()
.then (p => {
    console.log(p);
})
.catch(e => {
    console.log(e);
})